name: Build
on:
  workflow_dispatch:
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build
    - name: Upload Build
      uses: actions/upload-artifact@v2.3.1
      with:
        path: LinkShortner
